# Generated by Django 5.1.1 on 2024-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('boolean', models.BooleanField(blank=True, default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='tasks', to='todo_app.tag')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['datetime', 'boolean'],
            },
        ),
    ]
