# Generated by Django 5.1.1 on 2024-09-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['datetime', 'сompleted_task'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='boolean',
            new_name='сompleted_task',
        ),
    ]
